[package]
name = "data_structure"
version = "0.1.0"
edition = "2024"

[dependencies]
hex = "0.4.3"

[[bin]]
name = "data_structure"
path = "src/bin/main.rs"

[lib]
name = "data_structure_lib"
path = "src/lib/lib.rs"
